/project-folder
    /html
        index.html
        shop.html
        cart.html
        contact.html
    /css
        style.css
    /js
        script.js
    /images
        tshirt.jpg
        jeans.jpg
        jacket.jpg
        sneakers.jpg
